bind 127.0.0.1 ::1
protected-mode yes
port 6379
daemonize no
supervised no
dir /var/lib/g7pb/redis
appendonly yes
appendfilename "appendonly.aof"
save 300 10
maxmemory 128mb
maxmemory-policy allkeys-lru
